apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      my_app: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        my_app: hello-world
    spec:
      containers:
        - name: api
          image: gmile/workshop-app:v14
          env:
            - name: DATABASE_URL
              value: postgres://postgres@10.60.1.14:5432/my-test-db
          resources:
            requests:
              cpu: 1m
            limits:
              cpu: 50m
