apiVersion: v1
kind: Pod
metadata:
  name: my-db-pod
spec:
  containers:
    - name: db
      image: postgres:12.0-alpine
      env:
        - name: POSTGRES_DB
          value: my-test-db
      volumeMounts:
        - name: my-data
          mountPath: /var/lib/postgresql/data
          subPath: postgresql-folder
  volumes:
    - name: my-data
      persistentVolumeClaim:
        claimName: pvc-for-our-tests