apiVersion: v1
kind: Pod
metadata:
  name: app-advanced-pod
spec:
  containers:
    - name: api
      image: gmile/workshop-app:v14
      env:
        - name: DATABASE_URL
          value: postgres://postgres@localhost:5432/my-test-db
    - name: db
      image: postgres:12.0-alpine
      env:
        - name: POSTGRES_DB
          value: my-test-db
      volumeMounts:
        - name: my-data
          mountPath: /var/lib/postgresql/data
          subPath: postgresql-folder
  volumes:
    - name: my-data
      persistentVolumeClaim:
        claimName: pvc-for-our-tests
   nodeSelector:
      kubernetes.io/hostname: gke-k8s-sandbox-cluster--default-pool-39667ee9-rr0k