apiVersion: v1
kind: Service
metadata:
  name: my-public-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: {{ .Values.nodePort }}
      targetPort: 4000
  selector:
    my_app: hello-world